"use client";

import { StoryboardData } from "@/lib/types";
import FrameCard from "./FrameCard";
import ExportButton from "./ExportButton";

interface StoryboardDisplayProps {
  storyboard: StoryboardData;
  onBack: () => void;
}

export default function StoryboardDisplay({
  storyboard,
  onBack,
}: StoryboardDisplayProps) {
  const safeFilename = storyboard.productName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

  return (
    <div className="w-full max-w-[1100px] mx-auto px-6">
      {/* Top Bar */}
      <div className="flex items-center justify-between mb-8">
        <button
          onClick={onBack}
          className="px-4 py-2 border border-border text-text text-[13px] font-medium rounded-lg hover:bg-bg transition-colors"
        >
          &larr; Back
        </button>
        <ExportButton
          targetId="storyboard-export"
          filename={`storyboard-${safeFilename}`}
          storyboard={storyboard}
        />
      </div>

      {/* Storyboard Content */}
      <div id="storyboard-export">
        {/* Header */}
        <div className="bg-card border border-border rounded-xl p-8 mb-6">
          <h1 className="text-[24px] font-bold text-text mb-3">
            {storyboard.title}
          </h1>
          <div className="flex flex-wrap gap-x-6 gap-y-1 text-[13px]">
            <span className="text-text-secondary">
              <span className="font-medium text-text">Product:</span>{" "}
              {storyboard.productName}
            </span>
            <span className="text-text-secondary">
              <span className="font-medium text-text">Duration:</span>{" "}
              {storyboard.duration}
            </span>
            <span className="text-text-secondary">
              <span className="font-medium text-text">Frames:</span>{" "}
              {storyboard.totalFrames}
            </span>
          </div>
        </div>

        {/* Frames */}
        <div className="flex flex-col gap-4">
          {storyboard.frames.map((frame) => (
            <FrameCard key={frame.sceneNumber} frame={frame} />
          ))}
        </div>

        {/* Footer */}
        <div className="mt-6 py-4 text-center">
          <p className="text-[11px] text-text-secondary/50 tracking-wide uppercase">
            Generated by Storyboard Generator
          </p>
        </div>
      </div>
    </div>
  );
}
